// =============================================================================
// goose-provider-regen.test.mjs — byte-exact lockstep guard for the goose-server
// kit's shipped custom_usai.json provider definition.
//
// The goose-server kit ships a committed custom_providers/custom_usai.json that is
// GENERATED by the USAi catalog goose emitter. This test is the load-bearing
// guarantee that the two stay in lockstep: emitting from the SAME catalog.json
// that ships in this repo must reproduce the committed kit file BYTE-FOR-BYTE.
//
// If catalog.json changes and someone forgets to regenerate the kit file (re-run
// the emitter and write its output to the kit path), this test fails CI.
//
// It also asserts the committed artifact carries NO key material — belt-and-
// suspenders, since it is a shipped file that ends up on disk inside the kit.
//
// The test reads the REAL shipped files via relative paths (NOT copied fixtures),
// so drift fails CI. Mirrors models-json-regen.test.mjs (prime-agent).
// =============================================================================

import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { test } from "node:test"

import { emitGooseProviderFromCatalog } from "../emitters/goose.mjs"

const HERE = path.dirname(fileURLToPath(import.meta.url))
const USAI_DIR = path.resolve(HERE, "..")
const REPO_ROOT = path.resolve(USAI_DIR, "../../..")

const CATALOG_JSON = path.join(USAI_DIR, "catalog.json")
const KIT_PROVIDER_JSON = path.join(
  REPO_ROOT,
  "integrations/isolation/acq-kits/goose-server/files/home/goose-config/custom_providers/custom_usai.json",
)

// On mismatch, find the first differing character offset and print a small window
// around it (expected vs actual) to make debugging fast.
function firstMismatchReport(expected, actual) {
  const len = Math.min(expected.length, actual.length)
  let i = 0
  for (; i < len; i++) {
    if (expected[i] !== actual[i]) break
  }
  const ctx = 40
  const from = Math.max(0, i - ctx)
  const to = i + ctx
  return [
    `first mismatch at offset ${i}`,
    `  expected len=${expected.length} actual len=${actual.length}`,
    `  expected: ${JSON.stringify(expected.slice(from, to))}`,
    `  actual:   ${JSON.stringify(actual.slice(from, to))}`,
  ].join("\n")
}

test("committed kit custom_usai.json equals the emitter output byte-for-byte", () => {
  const committed = readFileSync(KIT_PROVIDER_JSON, "utf8")
  const catalog = JSON.parse(readFileSync(CATALOG_JSON, "utf8"))
  const emitted = emitGooseProviderFromCatalog(catalog)

  if (committed !== emitted) {
    // Print a targeted diff before the assertion fails: this signals the kit file
    // is stale — regenerate it by re-running the emitter and writing its output
    // to the kit path.
    // eslint-disable-next-line no-console
    console.error(firstMismatchReport(emitted, committed))
  }
  assert.strictEqual(
    committed,
    emitted,
    "committed goose-server custom_usai.json is stale — regenerate from catalog.json via the USAi catalog goose emitter",
  )
})

test("committed kit custom_usai.json ships every catalog model and the env-var-name api_key_env", () => {
  const catalog = JSON.parse(readFileSync(CATALOG_JSON, "utf8"))
  const committed = JSON.parse(readFileSync(KIT_PROVIDER_JSON, "utf8"))
  assert.ok(Array.isArray(committed.models), "models must be an array")
  // DERIVED from the catalog, never a hardcoded count.
  assert.ok(catalog.models.length > 0, "catalog must not be empty")
  assert.equal(
    committed.models.length,
    catalog.models.length,
    "kit custom_usai.json must ship exactly the catalog's models",
  )
  assert.equal(
    committed.api_key_env,
    "CUSTOM_USAI_API_KEY",
    "api_key_env must be the goose guest's env-var NAME, never a secret",
  )
  assert.equal(committed.name, "custom_usai", "provider name Desktop selects")
})

test("committed kit custom_usai.json contains NO key material (shipped artifact)", () => {
  const committed = readFileSync(KIT_PROVIDER_JSON, "utf8")
  assert.doesNotMatch(committed, /api-key-/i)
  assert.doesNotMatch(committed, /\bsk-[A-Za-z0-9]/)
  assert.doesNotMatch(committed, /Bearer\s+\S/i)
  assert.doesNotMatch(committed, /[A-Za-z0-9+/]{32,}={0,2}/, "no long base64-ish secret blob")
  assert.doesNotMatch(committed, /\b[0-9a-f]{32,}\b/i, "no long hex secret blob")
})
