// =============================================================================
// models-json-regen.test.mjs — byte-exact lockstep guard for the prime-agent
// kit's shipped models.json.
//
// The prime-agent kit ships a committed models.json that is GENERATED by the
// USAi catalog prime-agent emitter. This test is the load-bearing guarantee
// that the two stay in lockstep: emitting from the SAME catalog.json that ships
// in this repo must reproduce the committed kit models.json BYTE-FOR-BYTE.
//
// If catalog.json changes and someone forgets to regenerate the kit models.json
// (re-run the emitter and write its output to the kit path), this test fails CI.
//
// It also asserts the committed artifact carries NO key material — belt-and-
// suspenders, since it is a shipped file that ends up on disk inside the kit.
//
// The test reads the REAL shipped files via relative paths (NOT copied
// fixtures), so drift fails CI. Mirrors the byte-exact pattern of the OpenCode
// emitter test (emitters.test.mjs).
// =============================================================================

import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { test } from "node:test"

import { emitPrimeAgentModelsFromCatalog } from "../emitters/prime-agent.mjs"

const HERE = path.dirname(fileURLToPath(import.meta.url))
const USAI_DIR = path.resolve(HERE, "..")
const REPO_ROOT = path.resolve(USAI_DIR, "../../..")

const CATALOG_JSON = path.join(USAI_DIR, "catalog.json")
const KIT_MODELS_JSON = path.join(
  REPO_ROOT,
  "integrations/isolation/acq-kits/prime-agent/files/home/prime-agent-config/models.json",
)

// On mismatch, find the first differing character offset and print a small
// window around it (expected vs actual) to make debugging fast.
function firstMismatchReport(expected, actual) {
  const len = Math.min(expected.length, actual.length)
  let i = 0
  for (; i < len; i++) {
    if (expected[i] !== actual[i]) break
  }
  const ctx = 40
  const from = Math.max(0, i - ctx)
  const to = i + ctx
  return [
    `first mismatch at offset ${i}`,
    `  expected len=${expected.length} actual len=${actual.length}`,
    `  expected: ${JSON.stringify(expected.slice(from, to))}`,
    `  actual:   ${JSON.stringify(actual.slice(from, to))}`,
  ].join("\n")
}

test("committed kit models.json equals the emitter output byte-for-byte", () => {
  const committed = readFileSync(KIT_MODELS_JSON, "utf8")
  const catalog = JSON.parse(readFileSync(CATALOG_JSON, "utf8"))
  const emitted = emitPrimeAgentModelsFromCatalog(catalog)

  if (committed !== emitted) {
    // Print a targeted diff before the assertion fails: this signals the kit
    // models.json is stale — regenerate it by re-running the emitter and
    // writing its output to the kit path.
    // eslint-disable-next-line no-console
    console.error(firstMismatchReport(emitted, committed))
  }
  assert.strictEqual(
    committed,
    emitted,
    "committed prime-agent kit models.json is stale — regenerate from catalog.json via the USAi catalog prime-agent emitter",
  )
})

test("committed kit models.json carries every catalog model and the env-var-name apiKey", () => {
  const catalog = JSON.parse(readFileSync(CATALOG_JSON, "utf8"))
  const committed = JSON.parse(readFileSync(KIT_MODELS_JSON, "utf8"))
  const provider = committed.providers.usai
  assert.ok(Array.isArray(provider.models), "providers.usai.models must be an array")
  // DERIVED from the catalog, never a hardcoded count: the gateway's model list
  // changes (models are added, renamed, or withdrawn), and a literal here goes
  // stale and fails for the wrong reason — hiding whether the artifact is
  // actually in lockstep with the catalog it is generated from.
  assert.ok(catalog.models.length > 0, "catalog must not be empty")
  assert.equal(
    provider.models.length,
    catalog.models.length,
    "kit models.json must ship exactly the catalog's models",
  )
  assert.equal(provider.apiKey, "USAI_API_KEY", "apiKey must be the env-var NAME, never a secret")
})

test("committed kit models.json contains NO key material (shipped artifact)", () => {
  const committed = readFileSync(KIT_MODELS_JSON, "utf8")
  // No value that looks like a real secret is present in the shipped file:
  //  - no `api-key-`/`sk-`/`Bearer ` prefixed strings,
  //  - no long base64-ish/hex blob that would look like a token.
  assert.doesNotMatch(committed, /api-key-/i)
  assert.doesNotMatch(committed, /\bsk-[A-Za-z0-9]/)
  assert.doesNotMatch(committed, /Bearer\s+\S/i)
  assert.doesNotMatch(committed, /[A-Za-z0-9+/]{32,}={0,2}/, "no long base64-ish secret blob")
  assert.doesNotMatch(committed, /\b[0-9a-f]{32,}\b/i, "no long hex secret blob")
})
